-- MySQL Script generated by MySQL Workbench
-- čt 26. března 2026, 13:18:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema objevy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema objevy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `objevy` DEFAULT CHARACTER SET utf8 COLLATE utf8_czech_ci ;
USE `objevy` ;

-- -----------------------------------------------------
-- Table `objevy`.`field`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `objevy`.`field` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `objevy`.`institution`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `objevy`.`institution` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `objevy`.`scientist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `objevy`.`scientist` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(45) NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  `bday` YEAR NOT NULL,
  `dday` YEAR NULL,
  `bplace` VARCHAR(45) NOT NULL,
  `field_id` INT NOT NULL,
  `institution_id` INT NOT NULL,
  PRIMARY KEY (`id`, `field_id`, `institution_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_scientist_field1_idx` (`field_id` ASC),
  INDEX `fk_scientist_institution1_idx` (`institution_id` ASC),
  CONSTRAINT `fk_scientist_field1`
    FOREIGN KEY (`field_id`)
    REFERENCES `objevy`.`field` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_scientist_institution1`
    FOREIGN KEY (`institution_id`)
    REFERENCES `objevy`.`institution` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `objevy`.`discovery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `objevy`.`discovery` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `year` VARCHAR(45) NOT NULL,
  `place` VARCHAR(45) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `objevy`.`scientist_has_discovery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `objevy`.`scientist_has_discovery` (
  `scientist_id` INT NOT NULL,
  `discovery_id` INT NOT NULL,
  PRIMARY KEY (`discovery_id`, `scientist_id`),
  INDEX `fk_scientist_has_discovery_discovery1_idx` (`discovery_id` ASC),
  INDEX `fk_scientist_has_discovery_scientist_idx` (`scientist_id` ASC),
  CONSTRAINT `fk_scientist_has_discovery_scientist`
    FOREIGN KEY (`scientist_id`)
    REFERENCES `objevy`.`scientist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_scientist_has_discovery_discovery1`
    FOREIGN KEY (`discovery_id`)
    REFERENCES `objevy`.`discovery` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
