-- MySQL Script generated by MySQL Workbench
-- čt 16. dubna 2026, 13:26:39
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema unikovka
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema unikovka
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `unikovka` DEFAULT CHARACTER SET utf8 COLLATE utf8_czech_ci ;
USE `unikovka` ;

-- -----------------------------------------------------
-- Table `unikovka`.`teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unikovka`.`teams` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `players` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unikovka`.`rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unikovka`.`rooms` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `capacity` INT NOT NULL,
  `notes` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unikovka`.`games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unikovka`.`games` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `difficulty` INT NOT NULL,
  `max_players` INT NOT NULL,
  `time` INT NOT NULL,
  `theme` VARCHAR(45) NULL,
  `teams_id` INT NOT NULL,
  `rooms_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_games_teams1_idx` (`teams_id` ASC),
  INDEX `fk_games_rooms1_idx` (`rooms_id` ASC),
  CONSTRAINT `fk_games_teams1`
    FOREIGN KEY (`teams_id`)
    REFERENCES `unikovka`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_games_rooms1`
    FOREIGN KEY (`rooms_id`)
    REFERENCES `unikovka`.`rooms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unikovka`.`voting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unikovka`.`voting` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `star` INT NOT NULL,
  `notes` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unikovka`.`tries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unikovka`.`tries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `time` INT NOT NULL,
  `sucess` TINYINT NOT NULL,
  `teams_id` INT NOT NULL,
  `games_id` INT NOT NULL,
  `voting_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_tries_teams1_idx` (`teams_id` ASC),
  INDEX `fk_tries_games1_idx` (`games_id` ASC),
  INDEX `fk_tries_voting1_idx` (`voting_id` ASC),
  CONSTRAINT `fk_tries_teams1`
    FOREIGN KEY (`teams_id`)
    REFERENCES `unikovka`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tries_games1`
    FOREIGN KEY (`games_id`)
    REFERENCES `unikovka`.`games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tries_voting1`
    FOREIGN KEY (`voting_id`)
    REFERENCES `unikovka`.`voting` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
